DROP USER IF EXISTS es_user;
CREATE ROLE es_user LOGIN ENCRYPTED PASSWORD 'md5583ecef431833886f6988de28d0f88c0' VALID UNTIL 'infinity';

GRANT ALL ON SCHEMA ES TO es_user;
GRANT ALL ON SCHEMA ESGeneric TO es_user;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ES TO es_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ESGeneric TO es_user;

GRANT SELECT ON ALL TABLES IN SCHEMA ES TO es_user;
GRANT SELECT ON ALL TABLES IN SCHEMA ESGeneric TO es_user;

GRANT INSERT ON ALL TABLES IN SCHEMA ES TO es_user;
GRANT INSERT ON ALL TABLES IN SCHEMA ESGeneric TO es_user;

GRANT UPDATE ON ALL TABLES IN SCHEMA ES TO es_user;
GRANT UPDATE ON ALL TABLES IN SCHEMA ESGeneric TO es_user;

GRANT DELETE ON ALL TABLES IN SCHEMA ES TO es_user;
GRANT DELETE ON ALL TABLES IN SCHEMA ESGeneric TO es_user;